version: '3.4'
services:
    nginx:
        ports:
            - "82:80"
            - "444:443"
    pgsql:
        ports:
            - "5433:5432"
    redis:
        ports:
            - "6380:6379"
    websockets:
        ports:
            - "${SOKETI_PORT:-6001}:6001"
            - "${SOKETI_METRICS_SERVER_PORT:-9601}:9601"
